$(document).ready(function() {
    $("#team1").click(function(){
        $(".team").slideUp(600);
        $("#team1_div").slideToggle(600);
    });
    $("#team2").click(function(){
        $(".team").slideUp(600);
        $("#team2_div").slideToggle(600);
    });
    $("#team3").click(function(){
        $(".team").slideUp(600);
        $("#team3_div").slideToggle(600);
    });
    $("#team4").click(function(){
        $(".team").slideUp(600);
        $("#team4_div").slideToggle(600);
    });
    $("#team5").click(function(){
        $(".team").slideUp(600);
        $("#team5_div").slideToggle(600);
    });
    $("#team6").click(function(){
        $(".team").slideUp(600);
        $("#team6_div").slideToggle(600);
    });
    $("#team7").click(function(){
        $(".team").slideUp(600);
        $("#team7_div").slideToggle(600);
    });
    $("#team8").click(function(){
        $(".team").slideUp(600);
        $("#team8_div").slideToggle(600);
    });
    $("#team9").click(function(){
        $(".team").slideUp(600);
        $("#team9_div").slideToggle(600);
    });
    $("#team10").click(function(){
        $(".team").slideUp(600);
        $("#team10_div").slideToggle(600);
    });
});